# Generated by Django 2.2.1 on 2019-06-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='标题')),
                ('description', models.CharField(blank=True, default='', max_length=128, verbose_name='详情')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='价格')),
                ('extension_code', models.CharField(max_length=64, verbose_name='插件ID')),
                ('extension_name', models.CharField(max_length=64, verbose_name='插件名')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '收据',
                'verbose_name_plural': '收据',
            },
        ),
    ]
