# Generated by Django 2.2 on 2020-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
