# Generated by Django 2.0 on 2017-12-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='qrcode_url',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='小程序码'),
        ),
    ]
