# Generated by Django 2.1.2 on 2018-10-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0002_wxuser_qrcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='testers',
            field=models.BooleanField(default=False, verbose_name='是否是测试人员'),
        ),
    ]
