# Generated by Django 2.1.2 on 2018-11-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_wxuser_testers'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='bonus_right',
            field=models.CharField(choices=[('true', '是'), ('false', '否'), ('null', '未达标')], default='null', max_length=32, verbose_name='分销反佣权利'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='rebate_right',
            field=models.CharField(choices=[('true', '是'), ('false', '否'), ('null', '未达标')], default='null', max_length=32, verbose_name='推广返利权利'),
        ),
    ]
