# Generated by Django 2.1.9 on 2019-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20181116_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='upload_prem',
            field=models.BooleanField(default=False, verbose_name='是否可以上传短视频'),
        ),
    ]
