# Generated by Django 2.1.8 on 2019-07-26 02:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0043_auto_20190430_0957'),
        ('shop', '0013_auto_20190619_1814'),
        ('wxapp', '0004_auto_20181116_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_id', models.CharField(max_length=64, verbose_name='快递公司客户编码')),
                ('delivery_id', models.CharField(max_length=64, verbose_name='快递公司ID')),
                ('password', models.CharField(max_length=64, verbose_name='快递公司客户密码')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '物流账号',
                'verbose_name_plural': '物流账号',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=128, verbose_name='打印员权限集')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_printers', to='shop.Shop', verbose_name='所属店铺')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_printers', to='wxapp.WxUser', verbose_name='打印员')),
            ],
            options={
                'verbose_name': '打印员',
                'verbose_name_plural': '打印员',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('wx_order_id', models.CharField(max_length=64, verbose_name='微信订单ID')),
                ('delivery_id', models.CharField(max_length=64, verbose_name='快递公司ID')),
                ('waybill_id', models.CharField(max_length=64, verbose_name='运单ID')),
                ('waybill_data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='运单信息')),
                ('items', models.ManyToManyField(related_name='delivery_records', to='trade.Items', verbose_name='子订单')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='trade.Orders', verbose_name='商品订单')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '运单记录',
                'verbose_name_plural': '运单记录',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('tel', models.CharField(blank=True, max_length=64, null=True, verbose_name='座机号码')),
                ('mobile', models.CharField(blank=True, max_length=64, null=True, verbose_name='手机号码')),
                ('company', models.CharField(blank=True, max_length=64, null=True, verbose_name='公司名称')),
                ('post_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='邮编')),
                ('country', models.CharField(blank=True, max_length=64, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=64, verbose_name='省份')),
                ('city', models.CharField(max_length=64, verbose_name='市/地区')),
                ('area', models.CharField(max_length=64, verbose_name='区/县')),
                ('address', models.CharField(max_length=512, verbose_name='详细地址')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '发件人信息',
                'verbose_name_plural': '发件人信息',
            },
        ),
    ]
