# Generated by Django 2.1.7 on 2019-02-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_shop_service_phone'),
        ('goods', '0044_auto_20190220_1653'),
        ('qfile', '0004_auto_20190222_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jump_type', models.CharField(choices=[('goods', '商品详情'), ('goods_type', '商品类型'), ('category', '商品分类')], max_length=128, verbose_name='跳转类型')),
                ('goods_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='商品类型')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='跳转分类')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='跳转商品')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='轮播图')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='模块名称')),
                ('module', models.CharField(max_length=128, verbose_name='模块')),
                ('active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '首页模块',
                'verbose_name_plural': '首页模块',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='快速入口名称')),
                ('jump_type', models.CharField(choices=[('goods_type', '商品类型'), ('category', '商品分类')], max_length=128, verbose_name='跳转类型')),
                ('goods_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='商品类型')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='跳转分类')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='快速入口图标')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '快捷入口',
                'verbose_name_plural': '快捷入口',
                'ordering': ('index',),
            },
        ),
    ]
