# Generated by Django 2.1.5 on 2019-02-27

from django.db import migrations, transaction


def init_module(apps, schema_editor):
    Shop = apps.get_model("shop", "Shop")
    Module = apps.get_model("homepage", "Module")
    shops = Shop.objects.all()
    with transaction.atomic():
        for shop in shops:
            Module.objects.get_or_create(shop=shop, label='拼团商品推荐', module='grouping',
                                         defaults={'active': True, 'index': 0})
            Module.objects.get_or_create(shop=shop, label='周期购商品推荐', module='periodic',
                                         defaults={'active': True, 'index': 1})
            Module.objects.get_or_create(shop=shop, label='热门商品推荐', module='recommendation',
                                         defaults={'active': True, 'index': 2})
            Module.objects.get_or_create(shop=shop, label='积分商品推荐', module='credit',
                                         defaults={'active': True, 'index': 3})


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
        ('shop', '0007_init_shop')
    ]

    operations = [
        migrations.RunPython(init_module),
    ]