# Generated by Django 2.1.10 on 2019-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_init_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='version_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='module',
            name='version_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='version_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
