# Generated by Django 2.1.4 on 2019-01-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0038_goods_groupbuy'),
        ('trade', '0033_auto_20190110_1810'),
        ('wxapp', '0004_auto_20181116_1501'),
        ('shop', '0003_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField(verbose_name='拼团倒计时')),
                ('integral', models.PositiveSmallIntegerField(default=0, verbose_name='奖励积分')),
                ('mode', models.CharField(choices=[('people', '参团人数'), ('goods', '购买数量')], max_length=30, verbose_name='成团方式')),
                ('ladder', models.TextField(verbose_name='拼团阶梯')),
            ],
            options={
                'verbose_name': '商品拼团信息',
                'verbose_name_plural': '商品拼团信息',
            },
        ),
        migrations.CreateModel(
            name='PtGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptgroup_no', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='拼团号')),
                ('ptgtype_id', models.PositiveIntegerField(verbose_name='规格的id')),
                ('mode', models.CharField(choices=[('people', '参团人数'), ('goods', '购买数量')], max_length=30, verbose_name='成团方式')),
                ('status', models.CharField(choices=[('build', '拼团中'), ('done', '已成团'), ('fail', '已取消')], default='build', max_length=30, verbose_name='拼团状态')),
                ('robot', models.PositiveSmallIntegerField(default=0, verbose_name='后台添加的机器人')),
                ('robot_goods', models.PositiveSmallIntegerField(default=0, verbose_name='后台添加的机器人购买数量')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='拼团发起时间')),
                ('end_time', models.DateTimeField(verbose_name='拼团结束时间')),
                ('order', models.ManyToManyField(related_name='pt_group', to='trade.Orders', verbose_name='拼团的订单')),
                ('partake', models.ManyToManyField(related_name='partake_team', to='wxapp.WxUser', verbose_name='参团人')),
                ('ptgoods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_goods', to='goods.Goods', verbose_name='拼团商品')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_pt', to='shop.Shop', verbose_name='所属商店')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='wxapp.WxUser', verbose_name='拼团发起人')),
            ],
            options={
                'verbose_name': '拼团',
                'verbose_name_plural': '拼团',
            },
        ),
    ]
