# Generated by Django 2.1.4 on 2019-01-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptgroup',
            name='goods_name',
            field=models.CharField(max_length=128, null=True, verbose_name='商品名称'),
        ),
    ]
