# Generated by Django 2.1.4 on 2019-01-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_buy', '0002_ptgroup_goods_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptgroup',
            name='ptgtype_id',
        ),
    ]
