# Generated by Django 2.0.7 on 2018-07-14 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
            ],
            options={
                'verbose_name': '首页轮播图片',
                'verbose_name_plural': '首页轮播图片',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='城市名', max_length=30, verbose_name='城市名')),
            ],
            options={
                'verbose_name': '定位城市',
                'verbose_name_plural': '定位城市',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '商品详情图',
                'verbose_name_plural': '商品详情图',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('goods_brief', models.TextField(max_length=256, verbose_name='商品简短描述')),
                ('free_postage', models.BooleanField(default=True, verbose_name='是否包邮')),
                ('postage', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='邮费')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='类别图')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='goods.Goods', verbose_name='商品')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='详情页轮播图')),
            ],
            options={
                'verbose_name': '详情页轮播图',
                'verbose_name_plural': '详情页轮播图',
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='规格', max_length=100, verbose_name='规格')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('goods', models.ForeignKey(help_text='规格', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品类别')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.City', verbose_name='所在地'),
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='detailimage',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='detailimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='详情图'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='轮播图'),
        ),
    ]
