# Generated by Django 2.0.7 on 2018-07-14 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtype',
            name='goods',
            field=models.ForeignKey(help_text='规格', on_delete=django.db.models.deletion.CASCADE, related_name='gtypes', to='goods.Goods', verbose_name='商品规格'),
        ),
    ]
