# Generated by Django 2.0.7 on 2018-07-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180714_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-index',), 'verbose_name': '首页轮播图片', 'verbose_name_plural': '首页轮播图片'},
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='价格'),
        ),
    ]
