# Generated by Django 2.0.7 on 2018-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180717_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtype',
            name='is_sell',
            field=models.BooleanField(default=True, verbose_name='是否在售'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='市场价格'),
        ),
    ]
