# Generated by Django 2.0.7 on 2018-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180719_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='a_type',
            field=models.CharField(choices=[('percent', '比例计算'), ('fixed', '固定金额'), ('null', '不单独设置')], default='null', max_length=20, verbose_name='分销方式'),
        ),
        migrations.AddField(
            model_name='goods',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='数值'),
        ),
    ]
