# Generated by Django 2.0.7 on 2018-07-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180724_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='num2',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位：%', verbose_name='二级上线比例值'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='a_type',
            field=models.CharField(choices=[('percent', '比例计算'), ('null', '不单独设置')], default='null', max_length=20, verbose_name='分销方式'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位：%', verbose_name='一级上线比例值'),
        ),
    ]
