# Generated by Django 2.0.7 on 2018-07-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180724_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('index',), 'verbose_name': '首页轮播图片', 'verbose_name_plural': '首页轮播图片'},
        ),
    ]
