# Generated by Django 2.0.7 on 2018-07-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180727_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='城市名', max_length=30, unique=True, verbose_name='城市名'),
        ),
    ]
