# Generated by Django 2.0.7 on 2018-08-01 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0001_initial'),
        ('goods', '0009_auto_20180727_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailimage',
            options={'ordering': ('index',), 'verbose_name': '商品详情图', 'verbose_name_plural': '商品详情图'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'ordering': ('index',), 'verbose_name': '详情页轮播图', 'verbose_name_plural': '详情页轮播图'},
        ),
        migrations.AddField(
            model_name='detailimage',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='goods',
            name='poster',
            field=models.OneToOneField(help_text=' (建议使用像素为750*720的png图片)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to='qfile.File', verbose_name='海报模板'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='qfile.File', verbose_name='封面图'),
        ),
    ]
