# Generated by Django 2.1.2 on 2018-10-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20180801_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='poster',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster', to='qfile.File', verbose_name='海报模板'),
        ),
    ]
