# Generated by Django 2.1.2 on 2018-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20181009_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.IntegerField(choices=[(0, '在售'), (1, '预览'), (2, '下架')], default=0, verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='库存'),
        ),
    ]
