# Generated by Django 2.1.2 on 2018-10-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20181010_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('status',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
