# Generated by Django 2.1.2 on 2018-10-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20181010_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='a_type',
            field=models.CharField(choices=[('percent', '比例计算'), ('null', '不单独设置')], default='percent', max_length=20, verbose_name='分销方式'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='asset_ratio_1',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位：%', verbose_name='返利比例值'),
        ),
    ]
