# Generated by Django 2.1.2 on 2018-10-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20181011_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ('index', '-is_active'), 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'ordering': ('index',), 'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='asset_ratio',
            field=models.PositiveSmallIntegerField(default=0, help_text='单位：%', verbose_name='返利比例'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='优先级'),
        ),
    ]
