# Generated by Django 2.1.2 on 2018-10-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20181022_1131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('status', 'index'), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='index',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
    ]
