# Generated by Django 2.1.2 on 2018-10-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20181022_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ('-is_active', 'index'), 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
    ]
