# Generated by Django 2.1.2 on 2018-11-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_hotword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodtype',
            options={'ordering': ('-is_sell', 'index'), 'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
    ]
