# Generated by Django 2.1.2 on 2018-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_auto_20181105_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtype',
            name='buy_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='限购'),
        ),
    ]
