# Generated by Django 2.1.2 on 2018-12-03 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_goodtype_buy_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodtype',
            name='change_limit',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='改变限购时间'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='original_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='原版限购'),
        ),
    ]
