# Generated by Django 2.1.4 on 2018-12-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_auto_20181211_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('status', 'index'), 'permissions': (('create_template', '创建商品模板'),), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goodtype',
            options={'ordering': ('-is_sell', 'index'), 'permissions': (('change_rebate_bonus', '修改返利分销金额'),), 'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
    ]
