# Generated by Django 2.1.4 on 2018-12-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0029_auto_20181221_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='goods_type',
            field=models.CharField(choices=[('goods', '普通商品'), ('subgoods', '订阅商品')], default='goods', max_length=128, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subgoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.SubGoods', verbose_name='订阅商品'),
        ),
    ]
