# Generated by Django 2.1.4 on 2018-12-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0001_initial'),
        ('goods', '0030_auto_20181222_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoods',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgoods_poster', to='qfile.File', verbose_name='海报模板'),
        ),
        migrations.AddField(
            model_name='subgoodstemplate',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_poster', to='qfile.File', verbose_name='海报模板'),
        ),
        migrations.AlterField(
            model_name='subgoods',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgoods_image', to='qfile.File', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='subgoodstemplate',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_image', to='qfile.File', verbose_name='封面图'),
        ),
    ]
