# Generated by Django 2.1.4 on 2019-01-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0001_initial'),
        ('goods', '0032_auto_20190104_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='图片')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='OrdGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', models.TextField(blank=True, null=True, verbose_name='预计时间')),
                ('gtypes', models.ManyToManyField(to='goods.GoodType', verbose_name='普通商品规格')),
            ],
            options={
                'verbose_name': '普通商品',
                'verbose_name_plural': '普通商品',
            },
        ),
        migrations.RemoveField(
            model_name='goods',
            name='free_postage',
        ),
        migrations.AddField(
            model_name='goods',
            name='delivery_method',
            field=models.CharField(choices=[('own', '自配送'), ('express', '快递')], default='express', max_length=128, verbose_name='配送方式'),
        ),
        migrations.AddField(
            model_name='goods',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通商品'), ('sub', '订阅商品')], default='ord', max_length=128, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='goods',
            name='pick_up',
            field=models.BooleanField(default=False, verbose_name='是否允许自提'),
        ),
        migrations.AddField(
            model_name='goods',
            name='postage_setup',
            field=models.CharField(choices=[('free', '免邮'), ('distance', '按距离计算')], default='free', max_length=128, verbose_name='运费设置'),
        ),
        migrations.AddField(
            model_name='goods',
            name='sub_goods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.SubGoods', verbose_name='订阅商品'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_banner', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='postage',
            field=models.TextField(blank=True, null=True, verbose_name='运费'),
        ),
        migrations.AddField(
            model_name='goods',
            name='banner',
            field=models.ManyToManyField(related_name='banners_goods', to='goods.Images', verbose_name='详情页轮播图'),
        ),
        migrations.AddField(
            model_name='goods',
            name='detail',
            field=models.ManyToManyField(related_name='details_goods', to='goods.Images', verbose_name='商品详情图'),
        ),
        migrations.AddField(
            model_name='goods',
            name='ord_goods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.OrdGoods', verbose_name='普通商品'),
        ),
    ]
