# Generated by Django 2.1.4 on 2019-01-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0038_goods_groupbuy'),
        ('group_buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='groupbuy_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupbuy_goods', to='group_buy.GroupBuyInfo', verbose_name='拼团信息'),
        ),
        migrations.AddField(
            model_name='goodtype',
            name='ladder',
            field=models.TextField(blank=True, null=True, verbose_name='阶梯'),
        ),
        migrations.AddField(
            model_name='subgoodstype',
            name='ladder',
            field=models.TextField(blank=True, null=True, verbose_name='阶梯'),
        ),
    ]
