# Generated by Django 2.1.5 on 2019-02-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_auto_20190130_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='attach',
            name='option',
            field=models.TextField(null=True, verbose_name='选项'),
        ),
    ]
