# Generated by Django 2.1.5 on 2019-02-20 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_attach_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodtype',
            name='change_limit',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='改变限购时间'),
        ),
    ]
