# Generated by Django 2.1.7 on 2019-03-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_auto_20190228_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='fictitious',
            field=models.BooleanField(default=False, verbose_name='虚拟商品'),
        ),
        migrations.AddField(
            model_name='goods',
            name='recommendation',
            field=models.BooleanField(default=False, verbose_name='热门商品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通商品'), ('sub', '订阅商品'), ('replace', '积分换购')], default='ord', max_length=128, verbose_name='商品类型'),
        ),
    ]
