# Generated by Django 2.1.7 on 2019-03-01 07:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0046_auto_20190301_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='预计时间')),
            ],
            options={
                'verbose_name': '积分商品',
                'verbose_name_plural': '积分商品',
            },
        ),
        migrations.CreateModel(
            name='ReplGoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='规格', max_length=100, verbose_name='规格')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='库存')),
                ('is_sell', models.BooleanField(default=True, verbose_name='是否在售')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='优先级')),
                ('buy_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='限购')),
                ('original_limit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='原版限购')),
                ('change_limit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='改变限购时间')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'ordering': ('-is_sell', 'index'),
            },
        ),
        migrations.AlterField(
            model_name='attach',
            name='option',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='replgoods',
            name='gtypes',
            field=models.ManyToManyField(to='goods.ReplGoodsType', verbose_name='积分商品规格'),
        ),
        migrations.AddField(
            model_name='goods',
            name='repl_goods',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.ReplGoods', verbose_name='积分商品'),
        ),
    ]
