# Generated by Django 2.1.7 on 2019-03-01 07:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0047_auto_20190301_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordgoods',
            name='estimate_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='预计时间'),
        ),
    ]
