# Generated by Django 2.1.7 on 2019-04-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_auto_20190305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('own', '自配送'), ('express', '快递')], max_length=128, null=True, verbose_name='配送方式'),
        ),
    ]
