# Generated by Django 2.1.7 on 2019-04-24 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_delivery_method(apps, schema_editor):
    Goods = apps.get_model("goods", "Goods")
    for goods in Goods.objects.all():
        if goods.delivery_method:
            goods.delivery_method_list.append(goods.delivery_method)
        if goods.pick_up:
            goods.delivery_method_list.append('buyer')
        goods.save()




class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0051_auto_20190419_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='delivery_method_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('own', '商家自配送'), ('express', '快递配送'), ('buyer', '用户自提')], max_length=128), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='goods',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('own', '商家自配送'), ('express', '快递配送'), ('buyer', '用户自提')], max_length=128, null=True, verbose_name='配送方式'),
        ),
    ]
