# Generated by Django 2.1.7 on 2019-04-25 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0054_auto_201904024_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='delivery_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('own', '商家自配送'), ('express', '快递配送'), ('buyer', '用户自提')], max_length=128), default=list, size=None, verbose_name='配送方式'),
        ),
    ]
