# Generated by Django 2.1.7 on 2019-04-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0055_auto_20190425_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodtype',
            name='original_limit',
        ),
        migrations.RemoveField(
            model_name='replgoodstype',
            name='original_limit',
        ),
    ]
