# Generated by Django 2.1.7 on 2019-05-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0056_auto_20190426_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='image',
        ),
    ]
