# Generated by Django 2.1.9 on 2019-07-24 03:00

from django.db import migrations, models


def update_goods_status(apps, schema_editor):
    Goods = apps.get_model('goods', 'Goods')
    Goods.objects.filter(status=2).update(status=3)


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0058_auto_20190507_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(choices=[(0, '在售'), (1, '预览'), (2, '库存不足'), (3, '下架')], default=0, verbose_name='商品状态'),
        ),

        migrations.RunPython(update_goods_status)
    ]
