# Generated by Django 2.1.10 on 2019-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0059_auto_20190724_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='version_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
