# Generated by Django 2.2 on 2020-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0063_auto_20200108_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='subgoodstype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='sub_goods',
        ),
        migrations.AlterField(
            model_name='goods',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通商品'), ('replace', '积分换购')], default='ord', max_length=128, verbose_name='商品类型'),
        ),
        migrations.DeleteModel(
            name='SubGoods',
        ),
        migrations.DeleteModel(
            name='SubGoodsType',
        ),
    ]
