# Generated by Django 2.0.7 on 2018-07-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_type', models.CharField(choices=[('percent', '比例计算'), ('null', '不设置')], default='null', max_length=64, verbose_name='分销方式')),
                ('asset_ratio1', models.DecimalField(decimal_places=2, default=0, help_text='单位：%', max_digits=15, verbose_name='一级上线比例值')),
                ('asset_ratio2', models.DecimalField(decimal_places=2, default=0, help_text='单位：%', max_digits=15, verbose_name='二级上线比例值')),
            ],
            options={
                'verbose_name': '分销设置',
                'verbose_name_plural': '分销设置',
            },
        ),
    ]
