# Generated by Django 2.1.2 on 2018-10-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20181018_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqcontent',
            name='icon',
        ),
    ]
