# Generated by Django 2.1.2 on 2018-11-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20181025_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenBuy',
            fields=[
            ],
            options={
                'verbose_name': '开放购买',
                'verbose_name_plural': '开放购买',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.systemconfig',),
        ),
    ]
