# Generated by Django 2.1.2 on 2018-11-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_openbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
            ],
            options={
                'verbose_name': '推广设置',
                'verbose_name_plural': '推广设置',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.systemconfig',),
        ),
    ]
