# Generated by Django 2.1.2 on 2018-11-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='消息标题')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '店铺消息',
                'verbose_name_plural': '店铺消息',
                'ordering': ('index', '-create_time'),
            },
        ),
    ]
