# Generated by Django 2.1.2 on 2018-11-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_bonusswitch_boolconfig_level_rebateswitch_rechargetype_shareswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSwitch',
            fields=[
            ],
            options={
                'verbose_name': '购物车启用设置',
                'verbose_name_plural': '购物车启用设置',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.boolconfig',),
        ),
    ]
