# Generated by Django 2.1.2 on 2018-12-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_cartswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargetype',
            name='proposal',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
