# Generated by Django 2.1.2 on 2018-12-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_rechargetype_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSwitch',
            fields=[
            ],
            options={
                'verbose_name': '会员钱包启用设置',
                'verbose_name_plural': '会员钱包启用设置',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.boolconfig',),
        ),
    ]
