# Generated by Django 2.1.2 on 2018-12-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0001_initial'),
        ('config', '0013_walletswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='图标'),
        ),
    ]
