# Generated by Django 2.1.4 on 2018-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20181206_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
