# Generated by Django 2.1.5 on 2019-02-15

from django.db import migrations, models


def create_or_update_config(apps, schema_editor):
    BoolConfig = apps.get_model("config", "BoolConfig")
    open_buy, created = BoolConfig.objects.get_or_create(name='open_buy', defaults={'content': 'true'})
    open_buy.label = '是否开放购买'
    open_buy.save()

    bonus_switch, created = BoolConfig.objects.get_or_create(name='bonus_switch', defaults={'content': 'true'})
    bonus_switch.label = '是否打开分销返利'
    bonus_switch.save()

    rebate_switch, created = BoolConfig.objects.get_or_create(name='rebate_switch', defaults={'content': 'true'})
    rebate_switch.label = '是否打开推广返利'
    rebate_switch.save()


    share_switch, created = BoolConfig.objects.get_or_create(name='share_switch', defaults={'content': 'true'})
    share_switch.label = '是否显示分享'
    share_switch.save()

    cart_switch, created = BoolConfig.objects.get_or_create(name='cart_switch', defaults={'content': 'true'})
    cart_switch.label = '是否开启购物车'
    cart_switch.save()

    wallet_switch, created = BoolConfig.objects.get_or_create(name='wallet_switch', defaults={'content': 'true'})
    wallet_switch.label = '是否启用会员钱包'
    wallet_switch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_systemconfig_label'),
    ]

    operations = [
        migrations.RunPython(create_or_update_config),
    ]