# Generated by Django 2.1.5 on 2019-02-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_create_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusSwitch',
        ),
        migrations.DeleteModel(
            name='CartSwitch',
        ),
        migrations.DeleteModel(
            name='OpenBuy',
        ),
        migrations.DeleteModel(
            name='RebateSwitch',
        ),
        migrations.DeleteModel(
            name='ShareSwitch',
        ),
        migrations.DeleteModel(
            name='WalletSwitch',
        ),
    ]
