# Generated by Django 2.1.5 on 2019-02-27

from django.db import migrations, models


def create_or_update_config(apps, schema_editor):
    BoolConfig = apps.get_model("config", "BoolConfig")
    open_buy, created = BoolConfig.objects.get_or_create(name='tradition_home', defaults={'content': 'true'})
    open_buy.label = '使用传统首页'
    open_buy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_auto_20190215_1555'),
    ]

    operations = [
        migrations.RunPython(create_or_update_config),
    ]