# Generated by Django 2.1.7 on 2019-03-13 06:18

from django.db import migrations



def create_version_config(apps, schema_editor):
    Version = apps.get_model("config", "Version")
    Version.objects.get_or_create(name='version', defaults={'label': '后台服务器版本'})


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_home_page_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
            ],
            options={
                'verbose_name': '后台版本',
                'verbose_name_plural': '后台版本',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.systemconfig',),
        ),

        migrations.RunPython(create_version_config),
    ]