# Generated by Django 2.1.7 on 2019-03-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0004_auto_20190222_1822'),
        ('config', '0021_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True, verbose_name='图片配置项')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qfile.File', verbose_name='图片')),
            ],
            options={
                'verbose_name': '平台图片配置',
                'verbose_name_plural': '平台图片配置',
            },
        ),
    ]
