# Generated by Django 2.1.7 on 2019-03-13 06:18

from django.db import migrations



def create_show_copyright_config(apps, schema_editor):
    BoolConfig = apps.get_model("config", "BoolConfig")
    open_buy, created = BoolConfig.objects.get_or_create(name='show_copyright', defaults={'content': 'true'})
    open_buy.label = '是否显示技术支持'
    open_buy.save()


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_storelogo'),
    ]

    operations = [
        migrations.RunPython(create_show_copyright_config),
    ]