# Generated by Django 2.2.1 on 2019-05-14 02:11

from django.db import migrations


def create_configs(apps, schema_editor):
    config = apps.get_model('config', 'BoolConfig')
    config.objects.get_or_create(
        name='store_type',
        label='店铺类型',
        defaults={'content': 'camel'},
    )
    config.objects.get_or_create(
        name='attach_switch',
        label='是否启用自定义商品信息',
        defaults={'content': 'true'},
    )
    config.objects.get_or_create(
        name='qr_pay_switch',
        label='是否启用线下扫码支付',
        defaults={'content': 'true'},
    )
    config.objects.get_or_create(
        name='subscription_switch',
        label='是否启用周期购',
        defaults={'content': 'true'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_sms_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
            ],
            options={
                'verbose_name': '店铺类型',
                'verbose_name_plural': '店铺类型',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.systemconfig',),
        ),
        migrations.RunPython(create_configs),
    ]
