# Generated by Django 2.2.1 on 2019-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_storetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256, verbose_name='变量名')),
                ('value', models.TextField(verbose_name='变量值')),
            ],
        ),
    ]
