# Generated by Django 2.2.1 on 2019-07-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_datetime_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreName',
            fields=[
            ],
            options={
                'verbose_name': '店铺名称',
                'verbose_name_plural': '店铺名称',
                'proxy': True,
                'indexes': [],
            },
            bases=('config.systemconfig',),
        ),
    ]
