# Generated by Django 2.0.7 on 2018-07-17 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wxapp', '0002_wxuser_qrcode_url'),
        ('goods', '0003_auto_20180717_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('gtype_name', models.CharField(max_length=100, verbose_name='规格')),
                ('price', models.PositiveIntegerField(verbose_name='单价')),
                ('num', models.PositiveIntegerField(verbose_name='数量')),
                ('pay_status', models.CharField(choices=[('paying', '待付款'), ('sending', '待发货'), ('receiving', '待收货'), ('over', '已收货')], default='paying', max_length=30, verbose_name='订单状态')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='订单金额')),
                ('asset_mount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='佣金支付金额')),
                ('real_mount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实付金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address_info', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('express_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='签收人')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('region', models.CharField(default='', max_length=100, verbose_name='地区')),
                ('location_detail', models.CharField(default='', max_length=100, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.UserAddress'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_record', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='gtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodType'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wxapp.WxUser', verbose_name='微信用户'),
        ),
    ]
