# Generated by Django 2.0.7 on 2018-07-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('-is_default',), 'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
    ]
