# Generated by Django 2.0.7 on 2018-07-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180719_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'ordering': ('-add_time',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='express_company',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='市场价'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价'),
        ),
    ]
