# Generated by Django 2.0.7 on 2018-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_orderinfo_postage'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='邮编'),
        ),
    ]
