# Generated by Django 2.0.7 on 2018-07-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_orderinfo_g_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='电话'),
        ),
    ]
