# Generated by Django 2.0.7 on 2018-07-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20180726_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='singer_mobile',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
    ]
