# Generated by Django 2.1.2 on 2018-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20180727_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='remark',
            field=models.TextField(default='', verbose_name='备注'),
        ),
    ]
