# Generated by Django 2.1.2 on 2018-10-12 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20181011_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间'),
        ),
    ]
