# Generated by Django 2.1.2 on 2018-10-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20181012_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='flag_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('paying', '待付款'), ('sending', '待发货'), ('receiving', '待收货'), ('over', '已收货'), ('close', '已关闭')], db_index=True, default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
