# Generated by Django 2.1.2 on 2018-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20181016_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
