# Generated by Django 2.1.2 on 2018-10-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20181017_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='share_openid',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='share_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='分享用户的ID'),
        ),
    ]
