# Generated by Django 2.1.2 on 2018-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20181017_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='快递公司名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '快递公司',
                'verbose_name_plural': '快递公司',
            },
        ),
    ]
