# Generated by Django 2.1.2 on 2018-10-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_express'),
    ]

    operations = [
        migrations.AlterField(
            model_name='express',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='快递公司名称'),
        ),
    ]
