# Generated by Django 2.1.2 on 2018-11-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20181030_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信交易号'),
        ),
    ]
