# Generated by Django 2.1.2 on 2018-11-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_wxuser_testers'),
        ('goods', '0021_auto_20181105_1623'),
        ('trade', '0017_orderinfo_trade_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('g_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品封面图url')),
                ('gtype_name', models.CharField(max_length=100, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='市场价')),
                ('postage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='邮费')),
                ('num', models.PositiveIntegerField(verbose_name='数量')),
                ('share_user_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='分享用户的ID')),
                ('g_rebate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='返利金额')),
                ('g_bonus', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='分销金额')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('express_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('express_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司')),
                ('status', models.CharField(choices=[('paying', '待付款'), ('sending', '待发货'), ('receiving', '待收货'), ('over', '已收货'), ('close', '已关闭')], db_index=True, default='paying', max_length=30, verbose_name='状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Goods', verbose_name='商品')),
                ('gtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.GoodType')),
            ],
            options={
                'verbose_name': '订单的商品',
                'verbose_name_plural': '订单的商品',
                'ordering': ('add_time',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信交易号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('paying', '待付款'), ('has paid', '已付款'), ('done', '交易成功'), ('close', '交易关闭')], db_index=True, default='paying', max_length=30, verbose_name='订单状态')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='订单金额')),
                ('postage_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='总邮费')),
                ('real_mount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实付金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address_info', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('singer_mobile', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
                ('inv_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头类型')),
                ('inv_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头名称')),
                ('inv_taxNumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头税号')),
                ('inv_companyAddress', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位地址')),
                ('inv_telephone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号码')),
                ('inv_bankName', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行名称')),
                ('inv_bankAccount', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行账号')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.UserAddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='wxapp.WxUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-add_time',),
            },
        ),
        migrations.AddField(
            model_name='goodsitems',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='trade.Order', verbose_name='所属订单'),
        ),
    ]
