# Generated by Django 2.1.2 on 2018-11-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_auto_20181107_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-add_time',), 'verbose_name': '新版订单', 'verbose_name_plural': '新版订单'},
        ),
    ]
