# Generated by Django 2.1.2 on 2018-11-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_auto_20181116_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsitems',
            options={'ordering': ('-add_time',), 'verbose_name': '订单的商品', 'verbose_name_plural': '订单的商品'},
        ),
    ]
