# Generated by Django 2.1.2 on 2018-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0020_auto_20181123_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='asset_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用收益支付的金额'),
        ),
        migrations.AddField(
            model_name='order',
            name='recharge_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用充值支付的金额'),
        ),
    ]
