# Generated by Django 2.1.2 on 2018-12-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0021_auto_20181130_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsitems',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收货时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paying', '待付款'), ('has paid', '待发货'), ('receiving', '待收货'), ('done', '交易成功'), ('close', '交易关闭')], db_index=True, default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
