# Generated by Django 2.1.4 on 2018-12-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0023_auto_20181211_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_name',
        ),
    ]
