# Generated by Django 2.1.4 on 2018-12-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20181116_1501'),
        ('goods', '0029_auto_20181221_1306'),
        ('shop', '0003_shop_status'),
        ('trade', '0024_remove_order_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField(verbose_name='期数')),
                ('send_date', models.DateField(verbose_name='配送日期')),
                ('send_start', models.TimeField(blank=True, null=True, verbose_name='配送日开始配送时间')),
                ('send_end', models.TimeField(blank=True, null=True, verbose_name='配送日结束配送时间')),
                ('send_type', models.CharField(choices=[('sending', '待发货'), ('receiving', '待收货'), ('arrive', '备货中'), ('over', '已收货')], default='sending', max_length=128, verbose_name='配送状态')),
                ('express_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('express_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
            ],
            options={
                'verbose_name': '订阅订单周期',
                'verbose_name_plural': '订阅订单周期',
                'ordering': ('cycle',),
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信交易号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '服务中'), (1, '待付款'), (2, '已完成'), (3, '已关闭')], db_index=True, default=1, verbose_name='订单状态')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('g_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品封面图url')),
                ('gtype_name', models.CharField(max_length=100, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='原价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='市场价')),
                ('cycle_num', models.PositiveSmallIntegerField(verbose_name='订阅期数')),
                ('delivery_setup', models.CharField(choices=[('date', '配送日期'), ('interval', '固定间隔')], default='interval', max_length=128, verbose_name='配送设置')),
                ('date_setup', models.CharField(blank=True, choices=[('specific', '具体日期'), ('weekly', '每周')], max_length=128, null=True, verbose_name='配送时间设置')),
                ('delivery_data', models.TextField(blank=True, null=True, verbose_name='配送日期')),
                ('interval', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='固定间隔')),
                ('start_send_date', models.DateField(verbose_name='开始配送日期')),
                ('send_start_time', models.TimeField(blank=True, null=True, verbose_name='配送日开始配送时间')),
                ('send_end_time', models.TimeField(blank=True, null=True, verbose_name='配送日结束配送时间')),
                ('order_mount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='订单金额')),
                ('postage', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='总邮费')),
                ('real_mount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实付金额')),
                ('asset_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用收益支付的金额')),
                ('recharge_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用充值支付的金额')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='折扣')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
                ('delivery_method', models.CharField(choices=[('own', '商家自配送'), ('express', '快递配送'), ('buyer', '用户自提')], max_length=128, verbose_name='配送方式')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='下次配送时间')),
                ('address_info', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('singer_mobile', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('inv_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头类型')),
                ('inv_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头名称')),
                ('inv_taxNumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头税号')),
                ('inv_companyAddress', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位地址')),
                ('inv_telephone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号码')),
                ('inv_bankName', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行名称')),
                ('inv_bankAccount', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行账号')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.UserAddress')),
                ('gtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.SubGoodsType', verbose_name='商品规格')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
                ('subgoods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.SubGoods', verbose_name='订阅商品')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborder', to='wxapp.WxUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '订阅商品订单',
                'verbose_name_plural': '订阅商品订单',
                'ordering': ('status', 'next_send'),
            },
        ),
        migrations.AddField(
            model_name='cycleitems',
            name='suborder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.SubOrder', verbose_name='订阅订单'),
        ),
    ]
