# Generated by Django 2.1.4 on 2018-12-22 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0025_auto_20181221_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suborder',
            options={'ordering': ('status', 'next_send', '-add_time'), 'verbose_name': '订阅商品订单', 'verbose_name_plural': '订阅商品订单'},
        ),
        migrations.AddField(
            model_name='suborder',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cycleitems',
            name='send_type',
            field=models.CharField(choices=[('sending', '待发货/备货中'), ('receiving', '待收货/待取件'), ('arrive', '送达/提件'), ('over', '已收货')], default='sending', max_length=128, verbose_name='配送状态'),
        ),
    ]
