# Generated by Django 2.1.4 on 2019-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0026_auto_20181222_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
    ]
