# Generated by Django 2.1.4 on 2019-01-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0027_auto_20190103_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='gtype',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
