# Generated by Django 2.1.4 on 2019-01-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20181116_1501'),
        ('shop', '0003_shop_status'),
        ('goods', '0037_migrate_banner'),
        ('trade', '0028_auto_20190107_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_info', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('sign_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('mobile_phone', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('postcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '配送地址',
                'verbose_name_plural': '配送地址',
            },
        ),
        migrations.CreateModel(
            name='GoodsBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtype_id', models.PositiveIntegerField(verbose_name='规格的id', null=True)),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('g_image', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品封面图路径')),
                ('gtype_name', models.CharField(max_length=100, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='单价')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='原价')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='市场价')),
                ('num', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('share_user_id', models.CharField(null=True, blank=True, max_length=128, verbose_name='分享用户的ID')),
                ('g_rebate', models.DecimalField(max_digits=15, decimal_places=2, null=True, verbose_name='返利金额')),
                ('g_bonus', models.DecimalField(max_digits=15, decimal_places=2, null=True, verbose_name='分销金额')),
                ('delivery_method', models.CharField(choices=[('own', '商家自配送'), ('express', '快递配送'), ('buyer', '用户自提')], max_length=128, verbose_name='配送方式')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单商品信息',
                'verbose_name_plural': '订单商品信息',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头类型')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头名称')),
                ('taxNumber', models.CharField(blank=True, max_length=128, null=True, verbose_name='抬头税号')),
                ('companyAddress', models.CharField(blank=True, max_length=128, null=True, verbose_name='单位地址')),
                ('telephone', models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号码')),
                ('bankName', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行名称')),
                ('bankAccount', models.CharField(blank=True, max_length=128, null=True, verbose_name='银行账号')),
            ],
            options={
                'verbose_name': '发票信息',
                'verbose_name_plural': '发票信息',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='期数')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='配送日期')),
                ('send_start', models.TimeField(blank=True, null=True, verbose_name='配送日开始配送时间')),
                ('send_end', models.TimeField(blank=True, null=True, verbose_name='配送日结束配送时间')),
                ('send_type', models.CharField(choices=[('paying', '待付款'), ('sending', '待发货/备货中'), ('receiving', '待收货/待取件'), ('arrive', '送达/提件'), ('over', '已收货'), ('close', '已关闭')], default='sending', max_length=128, verbose_name='配送状态')),
                ('express_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('express_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递公司')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
                ('goods_backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.GoodsBackup', verbose_name='商品信息')),
            ],
            options={
                'verbose_name': '子订单',
                'verbose_name_plural': '子订单',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信交易号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('paying', '待付款'), ('has paid', '待发货'), ('receiving', '待收货'), ('serving', '服务中'), ('done', '交易成功'), ('close', '交易关闭')], db_index=True, default='paying', max_length=30, verbose_name='订单状态')),
                ('model_type', models.CharField(choices=[('ord', '普通订单'), ('sub', '订阅订单')], default='ord', max_length=128, verbose_name='订单类型')),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='订单金额')),
                ('postage_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='总邮费')),
                ('real_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='实付金额')),
                ('asset_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用收益支付的金额')),
                ('recharge_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='使用充值支付的金额')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='折扣')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('flag_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='时间标志')),
                ('next_send', models.DateTimeField(blank=True, null=True, verbose_name='下次配送时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('delivery_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.DeliveryAddress', verbose_name='配送地址信息')),
                ('invoice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.Invoice', verbose_name='发票信息')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_test', to='wxapp.WxUser', verbose_name='微信用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ('-add_time',),
            },
        ),
        migrations.CreateModel(
            name='OrdGoodsBackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', models.TextField(blank=True, null=True, verbose_name='预计时间')),
            ],
            options={
                'verbose_name': '普通商品特定信息',
                'verbose_name_plural': '普通商品特定信息',
            },
        ),
        migrations.CreateModel(
            name='SubGoodsBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_num', models.PositiveSmallIntegerField(verbose_name='订阅期数')),
                ('delivery_setup', models.CharField(choices=[('date', '配送日期'), ('interval', '固定间隔')], default='interval', max_length=128, verbose_name='配送设置')),
                ('date_setup', models.CharField(blank=True, choices=[('specific', '具体日期'), ('weekly', '每周')], max_length=128, null=True, verbose_name='配送时间设置')),
                ('delivery_data', models.TextField(blank=True, null=True, verbose_name='配送日期')),
                ('interval', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='固定间隔')),
                ('start_send_date', models.DateField(verbose_name='开始配送日期')),
                ('send_start_time', models.TimeField(blank=True, null=True, verbose_name='配送日开始配送时间')),
                ('send_end_time', models.TimeField(blank=True, null=True, verbose_name='配送日结束配送时间')),
            ],
            options={
                'verbose_name': '订阅商品特定信息',
                'verbose_name_plural': '订阅商品特定信息',
            },
        ),
        migrations.AddField(
            model_name='items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.Orders', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='goodsbackup',
            name='ord_goods_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.OrdGoodsBackUp', verbose_name='普通商品信息'),
        ),
        migrations.AddField(
            model_name='goodsbackup',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_backup', to='trade.Orders', verbose_name='所属订单'),
        ),
        migrations.AddField(
            model_name='goodsbackup',
            name='sub_goods_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.SubGoodsBackup', verbose_name='订阅商品信息'),
        ),
    ]
