# Generated by Django 2.1.4 on 2019-01-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0031_migrate_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
    ]
