# Generated by Django 2.1.4 on 2019-01-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0032_orders_receive_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='receive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收货时间'),
        ),
    ]
