# Generated by Django 2.1.4 on 2019-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0033_auto_20190110_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_pt',
            field=models.BooleanField(default=False, verbose_name='拼团订单'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('paying', '待付款'), ('has paid', '待发货'), ('receiving', '待收货'), ('serving', '服务中'), ('done', '交易成功'), ('close', '交易关闭'), ('groupbuy', '拼团中')], db_index=True, default='paying', max_length=30, verbose_name='订单状态'),
        ),
    ]
