# Generated by Django 2.1.5 on 2019-01-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0034_auto_20190116_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycleitems',
            name='suborder',
        ),
        migrations.RemoveField(
            model_name='goodsitems',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='goodsitems',
            name='gtype',
        ),
        migrations.RemoveField(
            model_name='goodsitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='goodsitems',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='gtype',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='subgoods',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='user',
        ),
        migrations.AddField(
            model_name='goodsbackup',
            name='attach',
            field=models.TextField(null=True, verbose_name='自定义字段'),
        ),
        migrations.DeleteModel(
            name='CycleItems',
        ),
        migrations.DeleteModel(
            name='GoodsItems',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
