# Generated by Django 2.1.7 on 2019-03-04 07:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0036_auto_20190220_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplGoodsBackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_time', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='预计时间')),
            ],
            options={
                'verbose_name': '换购商品特定信息',
                'verbose_name_plural': '换购商品特定信息',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通订单'), ('sub', '订阅订单'), ('repl', '积分换购订单')], default='ord', max_length=128, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='ordgoodsbackup',
            name='estimate_time',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='预计时间'),
        ),
        migrations.AddField(
            model_name='goodsbackup',
            name='repl_goods_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.ReplGoodsBackUp', verbose_name='积分换购商品信息'),
        ),
    ]
