# Generated by Django 2.1.7 on 2019-03-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0037_auto_20190304_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fictitious',
            field=models.BooleanField(blank=True, default=False, verbose_name='虚拟商品订单'),
        ),
    ]
