# Generated by Django 2.1.7 on 2019-03-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0039_auto_20190305_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wxapp.WxUser', verbose_name='微信用户'),
        ),
    ]
