# Generated by Django 2.1.7 on 2019-03-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0040_auto_20190306_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('id',), 'verbose_name': '子订单', 'verbose_name_plural': '子订单'},
        ),
    ]
