# Generated by Django 2.1.7 on 2019-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0041_auto_20190313_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='machine_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='支付终端号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通订单'), ('sub', '订阅订单'), ('repl', '积分换购订单'), ('qrpay', '线下支付订单')], default='ord', max_length=128, verbose_name='订单类型'),
        ),
    ]
