# Generated by Django 2.1.7 on 2019-04-30 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190429_1745'),
        ('trade', '0042_auto_20190326_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_no', models.CharField(max_length=10, verbose_name='自提号')),
                ('buyer_code', models.CharField(max_length=10, verbose_name='自提码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_code', to='trade.Items', verbose_name='所属子订单')),
            ],
            options={
                'verbose_name': '自提码',
                'verbose_name_plural': '自提码',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='entrust_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrusted_orders', to='shop.Shop', verbose_name='所属店铺'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.Shop', verbose_name='所属店铺'),
        ),
    ]
