# Generated by Django 2.1.8 on 2019-08-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0043_auto_20190430_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_count', models.IntegerField(verbose_name='导出次数')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_delivery', to='trade.Orders', verbose_name='所属订单')),
            ],
            options={
                'verbose_name': '订单导出记录',
                'verbose_name_plural': '订单导出记录',
            },
        ),
    ]
