# Generated by Django 2.1.8 on 2019-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0044_exportdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payjs_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PAYJS订单号'),
        ),
    ]
