# Generated by Django 2.1.8 on 2020-01-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0045_orders_payjs_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='credit',
            field=models.PositiveIntegerField(default=0, verbose_name='使用积分'),
        ),
        migrations.AddField(
            model_name='replgoodsbackup',
            name='credit',
            field=models.PositiveIntegerField(default=0, verbose_name='积分'),
        ),
    ]
