# Generated by Django 2.2 on 2020-01-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '00047_migrate_repl_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsbackup',
            name='sub_goods_info',
        ),
        migrations.AlterField(
            model_name='orders',
            name='model_type',
            field=models.CharField(choices=[('ord', '普通订单'), ('repl', '积分换购订单')], default='ord', max_length=128, verbose_name='订单类型'),
        ),
        migrations.DeleteModel(
            name='SubGoodsBackup',
        ),
    ]
