# Generated by Django 2.2 on 2020-01-19 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0048_auto_20200114_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payjs_order_id',
        ),
    ]
