# Generated by Django 2.0.2 on 2018-02-28 02:51

from django.db import migrations, models
import qsmstoken.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('dead_time', models.DateTimeField(default=qsmstoken.models.default_dead_time, verbose_name='Dead Time')),
            ],
            options={
                'verbose_name': 'SMS Token',
                'verbose_name_plural': 'SMS Token',
                'ordering': ('-create_time',),
            },
        ),
    ]
