# Generated by Django 2.1.9 on 2019-08-30 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0059_auto_20190724_1100'),
        ('wxapp', '0004_auto_20181116_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockWxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='封禁时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wxapp.WxUser', verbose_name='上传用户')),
            ],
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('browse', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('video', models.FileField(upload_to='shortvideo', verbose_name='短视频')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否公开')),
                ('size', models.IntegerField(default=0, verbose_name='短视频文件大小(MB)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('goods', models.ManyToManyField(to='goods.Goods', verbose_name='短视频推荐商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='wxapp.WxUser', verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '短视频',
                'verbose_name_plural': '短视频',
            },
        ),
    ]
