# Generated by Django 2.1.4 on 2018-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ManyToManyField(blank=True, related_name='shop', to='shop.Shop', verbose_name='所属店铺'),
        ),
    ]
