# Generated by Django 2.1.4 on 2019-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181212_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_all_user', '查看所有管理员'),), 'verbose_name': '管理员'},
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shop',
            field=models.ManyToManyField(blank=True, related_name='admin', to='shop.Shop', verbose_name='所属店铺'),
        ),
    ]
