# Generated by Django 2.0.7 on 2018-07-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('label', models.CharField(blank=True, db_index=True, help_text='不填写时，文件名称为上传文件：类型-名称', max_length=64, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='file', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件管理',
                'verbose_name_plural': '文件管理',
            },
        ),
    ]
