# Generated by Django 2.1.5 on 2019-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfile', '0002_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
