# Generated by Django 2.1.2 on 2018-10-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('turnovers', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='营业额')),
                ('order_count', models.PositiveIntegerField(verbose_name='订单量')),
            ],
            options={
                'verbose_name': '每日订单量营业额统计',
                'verbose_name_plural': '每日订单量营业额统计',
                'ordering': ('-date',),
            },
        ),
    ]
