# Generated by Django 2.1.4 on 2018-12-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='count',
            options={'ordering': ('-date',), 'permissions': (('view_total_count', '查看所有店汇总'),), 'verbose_name': '每日订单量营业额统计', 'verbose_name_plural': '每日订单量营业额统计'},
        ),
    ]
