# Generated by Django 2.1.4 on 2018-12-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_count_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
