# Generated by Django 2.1.7 on 2019-03-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_service_phone'),
        ('count', '0004_auto_20181215_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('new_num', models.PositiveIntegerField(default=0, verbose_name='新增反馈数量')),
                ('solve_num', models.PositiveIntegerField(default=0, verbose_name='解决反馈数量')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '每日用户反馈统计',
                'verbose_name_plural': '每日用户反馈统计',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('ord_num', models.PositiveIntegerField(default=0, verbose_name='普通订单数量')),
                ('sub_num', models.PositiveIntegerField(default=0, verbose_name='订阅订单数量')),
                ('repl_num', models.PositiveIntegerField(default=0, verbose_name='积分换购订单数量')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '每日订单统计',
                'verbose_name_plural': '每日订单统计',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='RechargeStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('recharge_num', models.PositiveIntegerField(default=0, verbose_name='充值数量')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='充值总金额')),
            ],
            options={
                'verbose_name': '每日充值统计',
                'verbose_name_plural': '每日充值统计',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='WithdrawStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('withdraw_num', models.PositiveIntegerField(default=0, verbose_name='申请提现数量')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='申请提现记录总金额')),
                ('succ_num', models.PositiveIntegerField(verbose_name='完成提现数量')),
            ],
            options={
                'verbose_name': '每日提现统计',
                'verbose_name_plural': '每日提现统计',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='WxUserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('new_user_num', models.PositiveIntegerField(default=0, verbose_name='新增用户数量')),
            ],
            options={
                'verbose_name': '每日新增用户统计',
                'verbose_name_plural': '每日新增用户统计',
                'ordering': ('-date',),
            },
        ),
    ]
