# Generated by Django 2.2 on 2020-01-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0008_auto_20190326_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatistics',
            name='sub_num',
        ),
        migrations.RemoveField(
            model_name='turnoversstatistics',
            name='sub_turnovers',
        ),
    ]
