# Generated by Django 2.1.4 on 2019-01-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_shop_status'),
        ('wxapp', '0004_auto_20181116_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('solve', models.BooleanField(default=False, verbose_name='是否解决')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Shop', verbose_name='所属店铺')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '买家反馈',
                'verbose_name_plural': '买家反馈',
                'ordering': ('solve', '-add_time'),
            },
        ),
    ]
