# Generated by Django 2.1.5 on 2019-02-13 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_feedback_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation', models.CharField(max_length=256, verbose_name='操作')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_log', to='feedback.FeedBack')),
            ],
            options={
                'verbose_name': '买家反馈处理日志',
                'verbose_name_plural': '买家反馈处理日志',
                'ordering': ('-add_time',),
            },
        ),
    ]
