# Generated by Django 2.0.7 on 2018-07-14 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wxapp', '0002_wxuser_qrcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('gtype', models.CharField(max_length=100, verbose_name='规格')),
                ('num', models.PositiveIntegerField(verbose_name='数量')),
                ('price', models.PositiveIntegerField(verbose_name='单价')),
                ('pay_status', models.CharField(choices=[('paying', '待付款'), ('sending', '待发货'), ('receiving', '待收货'), ('over', '已收货')], default='paying', max_length=30, verbose_name='订单状态')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='订单金额')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('address', models.CharField(default='', max_length=100, verbose_name='收货地址')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='签收人')),
                ('express_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_relations', to='wxapp.WxUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='wxapp.WxUser')),
            ],
            options={
                'verbose_name': '用户关系',
                'verbose_name_plural': '用户关系',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='WxUserAccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WxUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号码')),
                ('real_name', models.CharField(blank=True, default='', max_length=20, verbose_name='真实姓名')),
                ('scene', models.CharField(blank=True, default='', max_length=128, verbose_name='关注场景')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='wxapp.WxUser')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
