# Generated by Django 2.0.7 on 2018-07-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wxapp', '0002_wxuser_qrcode_url'),
        ('account', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_record', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wxapp.WxUser', verbose_name='微信用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userrelation',
            unique_together={('user', 'referral')},
        ),
    ]
