# Generated by Django 2.0.7 on 2018-07-24 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_wxuseraccountlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='referral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_relations', to='wxapp.WxUser'),
        ),
    ]
