# Generated by Django 2.1.2 on 2018-10-12 06:09

import apps.account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0003_wxuser_testers'),
        ('account', '0005_auto_20180724_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_no', models.CharField(default=apps.account.models.generate_wd_no, max_length=128, unique=True, verbose_name='提现单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='提现金额')),
                ('wx_code', models.CharField(max_length=128, verbose_name='微信号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='提现发起时间')),
                ('succ_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[(0, '提现中'), (1, '提现失败'), (2, '提现完成')], default=0, max_length=128, verbose_name='提现状态')),
                ('wxuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_logs', to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现记录',
                'verbose_name_plural': '提现记录',
                'ordering': ('status', '-add_time'),
            },
        ),
        migrations.AlterField(
            model_name='wxuseraccountlog',
            name='a_type',
            field=models.CharField(choices=[('asset', '分销'), ('use', '抵现'), ('use_return', '取消订单返还'), ('withdraw', '提现'), ('fail_withdraw_return', '提现失败返还')], max_length=32, verbose_name='类型'),
        ),
    ]
