# Generated by Django 2.1.2 on 2018-10-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181012_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.IntegerField(choices=[(0, '提现中'), (1, '提现失败'), (2, '提现完成')], default=0, verbose_name='提现状态'),
        ),
    ]
