# Generated by Django 2.1.2 on 2018-10-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20181012_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ('status', 'add_time'), 'verbose_name': '提现记录', 'verbose_name_plural': '提现记录'},
        ),
    ]
