# Generated by Django 2.1.2 on 2018-10-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0008_auto_20181013_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawOperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_no', models.CharField(db_index=True, max_length=128, verbose_name='提现单号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation', models.CharField(max_length=256, verbose_name='操作')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '提现操作日志',
                'verbose_name_plural': '提现操作日志',
                'ordering': ('-add_time',),
            },
        ),
    ]
