# Generated by Django 2.1.2 on 2018-10-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_withdrawoperationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuseraccountlog',
            name='number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='订单编号或提现编号'),
        ),
    ]
