# Generated by Django 2.1.2 on 2018-11-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_wxuseraccountlog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuseraccountlog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='消费金额'),
        ),
    ]
