# Generated by Django 2.1.2 on 2018-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20181102_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuseraccountlog',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='补充'),
        ),
    ]
