# Generated by Django 2.1.2 on 2018-11-22 09:05

import apps.account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_cartswitch'),
        ('wxapp', '0004_auto_20181116_1501'),
        ('account', '0013_wxuseraccountlog_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rchg_no', models.CharField(db_index=True, default=apps.account.models.generate_rg_no, max_length=128, unique=True, verbose_name='充值编号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='充值金额')),
                ('real_pay', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='支付金额')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信交易号')),
                ('status', models.CharField(choices=[('paid', '已支付'), ('unpaid', '未支付')], default='unpaid', max_length=128, verbose_name='充值状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('wxuser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_records', to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='config.Level', verbose_name='会员等级')),
                ('wxuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户等级',
                'verbose_name_plural': '用户等级',
            },
        ),
        migrations.AddField(
            model_name='wxuseraccount',
            name='recharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='充值余额'),
        ),
        migrations.AddField(
            model_name='wxuseraccount',
            name='total_recharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='累计充值实付金额'),
        ),
    ]
