# Generated by Django 2.1.2 on 2018-11-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20181123_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargerecord',
            name='wxuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_records', to='wxapp.WxUser', verbose_name='用户'),
        ),
    ]
