# Generated by Django 2.1.7 on 2019-03-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20190228_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuserintegrallog',
            name='log_type',
            field=models.CharField(choices=[('replace', '积分换购'), ('share', '分享奖励'), ('grouping', '拼团成功奖励'), ('gift', '店铺赠送'), ('deduction', '店铺扣减')], max_length=128, verbose_name='记录类型'),
        ),
    ]
