# Generated by Django 2.1.7 on 2019-03-01 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0004_auto_20181116_1501'),
        ('account', '0019_auto_20190301_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxUserCreditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('replace', '积分换购'), ('share', '分享奖励'), ('grouping', '拼团成功奖励'), ('gift', '店铺赠送'), ('deduction', '店铺扣减')], max_length=128, verbose_name='记录类型')),
                ('credit', models.PositiveIntegerField(default=0, verbose_name='积分')),
                ('remark', models.CharField(blank=True, default='', max_length=2048, verbose_name='备注')),
                ('note', models.CharField(blank=True, max_length=128, null=True, verbose_name='补充')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='增加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_logs', to='wxapp.WxUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分记录',
                'verbose_name_plural': '积分记录',
                'ordering': ('-add_time',),
            },
        ),
        migrations.RemoveField(
            model_name='wxuserintegrallog',
            name='user',
        ),
        migrations.RenameField(
            model_name='wxuseraccount',
            old_name='integral',
            new_name='credit',
        ),
        migrations.DeleteModel(
            name='WxUserIntegralLog',
        ),
    ]
