# Generated by Django 2.1.8 on 2019-10-16 07:31

import apps.sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_smsswitch_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveSmallIntegerField(default=0, verbose_name='短信余额')),
            ],
            options={
                'verbose_name': '短信余额',
                'verbose_name_plural': '短信余额',
            },
        ),
        migrations.CreateModel(
            name='SMSRechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_trade_no', models.CharField(default=apps.sms.models.generate_no, max_length=100, verbose_name='订单号')),
                ('transaction_id', models.CharField(max_length=100, null=True, verbose_name='微信交易号')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='充值金额')),
                ('num', models.PositiveSmallIntegerField(verbose_name='增加短信个数')),
                ('has_paid', models.BooleanField(default=False, verbose_name='是否已支付')),
                ('paid_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '短信服务充值记录',
                'verbose_name_plural': '短信服务充值记录',
            },
        ),
    ]
