# Generated by Django 2.1.4 on 2018-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'permissions': (('view_all_shop', '查看所有的店铺'),), 'verbose_name': '店铺', 'verbose_name_plural': '店铺'},
        ),
    ]
