# Generated by Django 2.1.4 on 2018-12-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181212_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('open', '营业中'), ('close', '休息中')], default='open', max_length=128, verbose_name='门店状态'),
        ),
    ]
