# Generated by Django 2.1.5 on 2019-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='service_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='客服电话'),
        ),
    ]
