# Generated by Django 2.1.7 on 2019-03-26 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_service_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=20, unique=True, verbose_name='终端号')),
                ('machine_sign', models.CharField(max_length=20, verbose_name='密钥')),
                ('qrcode_url', models.CharField(blank=True, default='', max_length=256, verbose_name='小程序码')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '云打印机',
                'verbose_name_plural': '云打印机',
            },
        ),
    ]
