# Generated by Django 2.1.7 on 2019-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='machine_name',
            field=models.CharField(default='', max_length=100, verbose_name='终端名'),
        ),
    ]
