# Generated by Django 2.1.7 on 2019-04-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_init_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_divide',
            field=models.CharField(choices=[('unlimit', '不限制'), ('radius', '半径划分'), ('geometry', '地图标注')], default='geometry', max_length=20, verbose_name='配送范围划分方式'),
        ),
        migrations.AddField(
            model_name='shop',
            name='delivery_radius',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='配送半径'),
        ),
        migrations.AddField(
            model_name='shop',
            name='entrust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Shop', verbose_name='委托店铺'),
        ),
    ]
