# Generated by Django 2.1.7 on 2019-04-29 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190429_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery_range',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='配送范围列表'),
        ),
    ]
