# Generated by Django 2.2.1 on 2019-05-22 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190429_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='device_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('speaker', '云音箱'), ('basic', '云打印机'), ('sheet', '云面单打印机')], max_length=128), default=list, size=None, verbose_name='设备类型'),
        ),
    ]
