# Generated by Django 2.2.1 on 2019-05-27 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_printer_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_url', models.CharField(blank=True, default='', max_length=256, verbose_name='小程序码')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Printer', verbose_name='设备')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '收款码',
                'verbose_name_plural': '收款码',
            },
        ),
    ]
