# Generated by Django 2.2.7 on 2019-12-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_version_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='tag',
            new_name='tags',
        ),
    ]
