# Generated by Django 2.2.7 on 2019-12-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191202_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
