# Generated by Django 2.2.7 on 2019-12-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peaple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='tags',
            field=models.ManyToManyField(blank=True, to='goods.Tag'),
        ),
        migrations.AddField(
            model_name='goods',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.Peaple'),
        ),
    ]
