# Generated by Django 2.2.7 on 2019-12-03 09:33

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('goods', '0005_auto_20191203_0913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peaple',
            new_name='People',
        ),
    ]
