# Generated by Django 2.2.7 on 2019-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20191203_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='version_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
