# Generated by Django 2.1.4 on 2019-01-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade', '0034_auto_20190116_2220'),
        ('wxapp', '0004_auto_20181116_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='退款单号')),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信退款单号')),
                ('real_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='微信支付退款金额')),
                ('asset_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='收益支付退款金额')),
                ('recharge_pay', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='充值支付退款金额')),
                ('refund_desc', models.CharField(max_length=255, verbose_name='退款原因')),
                ('status', models.CharField(choices=[('apply', '申请中'), ('refund', '已到账')], default='apply', max_length=30, verbose_name='退款状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('refund_time', models.DateTimeField(null=True, verbose_name='到账时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='trade.Orders', verbose_name='退款记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='wxapp.WxUser', verbose_name='微信用户')),
            ],
        ),
    ]
